// Shared types mirroring the generated static dataset (web/public/data).

export interface SystemInfo {
  os?: string | null
  os_version?: string | null
  cpu?: string | null
  cpu_cores_physical?: number | null
  cpu_cores_logical?: number | null
  gpu?: string | null
  gpu_vram_mb?: number | null
  npu?: string | null
  ram_gb?: number | null
  platform_name?: string | null
}

export interface RuntimeBlock {
  name: string
  version?: string | null
  backend?: string | null
  device?: string | null
}

export interface ModelBlock {
  name: string
  format?: string | null
  quantization?: string | null
  parameters?: string | null
  checksum?: string | null
}

export interface Metrics {
  load_time_ms?: number | null
  ttft_ms?: number | null
  prompt_tokens_per_second?: number | null
  generation_tokens_per_second?: number | null
  total_latency_ms?: number | null
  p50_latency_ms?: number | null
  p95_latency_ms?: number | null
  peak_ram_mb?: number | null
  peak_vram_mb?: number | null
  avg_cpu_util_percent?: number | null
  avg_gpu_util_percent?: number | null
  max_temperature_c?: number | null
  average_power_watts?: number | null
  performance_per_watt?: number | null
}

export interface Reproducibility {
  prompt?: string
  max_tokens?: number
  temperature?: number
  seed?: number
  context_length?: number
  warmup_runs?: number
  iterations?: number
  command?: string
  python_version?: string
  power_profile?: string
}

export interface BenchmarkResultDoc {
  schema_version: string
  run_id: string
  timestamp?: string
  trust_state?: string | null
  system?: SystemInfo
  runtime?: RuntimeBlock
  model?: ModelBlock
  metrics?: Metrics
  reproducibility?: Reproducibility
  _file?: string
}

export interface HardwareEntry {
  fingerprint: string
  cpu?: string | null
  gpu?: string | null
  npu?: string | null
  os?: string | null
  ram_gb?: number | null
  result_ids: string[]
}

export interface RuntimeEntry {
  name: string
  versions: string[]
  device_options: string[]
  result_ids: string[]
}

export interface ModelEntry {
  name: string
  format?: string | null
  quantizations: string[]
  checksums: string[]
  result_ids: string[]
}

export interface LeaderboardRow {
  /** Rank *within* the comparison group, not across the dataset. */
  rank: number
  /** Index of the comparison group this result belongs to. */
  group: number
  /** What the members of that group share (same model, runtime, workload). */
  group_label: string
  /** How many results are in the group; 1 means nothing to compare against. */
  group_size: number
  run_id: string
  runtime?: string | null
  model?: string | null
  cpu?: string | null
  gpu?: string | null
  value?: number | null
  /** Unit for performance-per-watt rows: tok/s/W and inf/s/W are different. */
  unit?: string | null
  /** Filterable dimensions. */
  vram_mb?: number | null
  vram_tier?: string | null
  quantization?: string | null
  device?: string | null
  trust?: string | null
}

export interface LeaderboardViews {
  throughput: LeaderboardRow[]
  ttft: LeaderboardRow[]
  perf_watt: LeaderboardRow[]
}

export interface TrendPoint {
  timestamp?: string
  version?: string | null
  throughput?: number | null
  ttft_ms?: number | null
}

export interface DatasetIndex {
  schema_version: string
  results_count: number
  hardware_count: number
  runtime_count: number
  model_count: number
  source_dir: string
  note: string
}

/** Reference case generated by the canonical Python fit estimator. */
export interface FitReferenceCase {
  parameters: string | null
  quantization: string | null
  available_vram_mb: number | null
  available_ram_mb: number | null
  context_tokens: number
  expected: {
    estimated_weights_gb: number | null
    estimated_total_gb: number | null
    fits: boolean | null
    fit_target?: string | null
    reason: string
  }
}

/**
 * Constants for the browser-side fit estimator, generated from
 * `aihwbench/analysis/fit.py` so the two implementations cannot drift.
 */
export interface FitConstants {
  bits_per_weight: Record<string, number>
  overhead_factor: number
  note: string
  reference_cases: FitReferenceCase[]
}

/** Verdict computed by the canonical Python classifier, for parity tests. */
export interface ComparabilityReferenceCase {
  a: string
  b: string
  classification: string
  machine_reasons: string[]
}

/**
 * The comparison-safety rule tables, generated from
 * `aihwbench/comparability.py` so the browser reaches the same verdict as
 * the CLI for any pair a reader picks.
 */
export interface ComparabilityRules {
  strict: string[]
  conditional: string[]
  required_present: string[]
  insufficient_metadata_reason: string
  reference_cases: ComparabilityReferenceCase[]
  empty_case: { classification: string; machine_reasons: string[] }
}

export interface ParetoPoint {
  run_id: string
  runtime?: string | null
  model?: string | null
  gpu?: string | null
  x: number
  y: number
  optimal: boolean
}

export interface ParetoView {
  x_metric: string
  y_metric: string
  x_higher_is_better: boolean
  y_higher_is_better: boolean
  points: ParetoPoint[]
  excluded_missing_metrics: number
}

export interface Dataset {
  index: DatasetIndex
  results: BenchmarkResultDoc[]
  hardware: HardwareEntry[]
  runtimes: RuntimeEntry[]
  models: ModelEntry[]
  leaderboard: LeaderboardViews
  trends: Record<string, TrendPoint[]>
  constants: FitConstants
  comparability: ComparabilityRules
  pareto: Record<string, ParetoView>
}