import { describe, it, expect } from 'vitest'
import {
  classify,
  NOT_COMPARABLE,
  STRICTLY_COMPARABLE,
  CONDITIONALLY_COMPARABLE,
} from '../src/lib/comparability'
import type { BenchmarkResultDoc, ComparabilityRules } from '../src/lib/types'
import rules from '../public/data/comparability.json'
import results from '../public/data/results.json'

// The compare view must reach the same verdict as `aihwbench compare`. The
// rule tables and a verdict for every published pair are generated by the
// canonical Python classifier; these tests replay them through the TypeScript
// one. A divergence is a failing build, not a wrong badge shown to a reader.

const RULES = rules as unknown as ComparabilityRules
const RESULTS = results as unknown as BenchmarkResultDoc[]

function byId(runId: string): BenchmarkResultDoc | undefined {
  return RESULTS.find((r) => r.run_id === runId)
}

describe('classify parity with the Python classifier', () => {
  it('has reference verdicts to check against', () => {
    expect(RULES.reference_cases.length).toBeGreaterThan(0)
  })

  for (const testCase of RULES.reference_cases) {
    it(`agrees on ${testCase.a} vs ${testCase.b}`, () => {
      const verdict = classify(RULES, byId(testCase.a), byId(testCase.b))
      expect(verdict.classification).toBe(testCase.classification)
      expect(verdict.machine_reasons).toEqual(testCase.machine_reasons)
    })
  }

  it('agrees that two empty documents are not comparable', () => {
    const verdict = classify(RULES, {} as BenchmarkResultDoc, {} as BenchmarkResultDoc)
    expect(verdict.classification).toBe(RULES.empty_case.classification)
    expect(verdict.machine_reasons).toEqual(RULES.empty_case.machine_reasons)
  })
})

describe('classify rules', () => {
  type Doc = Record<string, Record<string, unknown>>

  const base = (): Doc => ({
    model: { name: 'm', quantization: 'q4_k_m' },
    runtime: { name: 'ollama', backend: 'http', device: 'cuda', version: '1.0' },
    system: { cpu: 'CPU', gpu: 'GPU' },
    reproducibility: { iterations: 5, warmup_runs: 2 },
  })

  const doc = (value: Doc) => value as unknown as BenchmarkResultDoc

  /** A copy of `base()` with one dotted field changed or removed. */
  function variant(path: string, value?: unknown): Doc {
    const [section, key] = path.split('.') as [string, string]
    const copy = base()
    const target = copy[section] as Record<string, unknown>
    if (value === undefined) delete target[key]
    else target[key] = value
    return copy
  }

  it('calls identical runs strictly comparable', () => {
    expect(classify(RULES, doc(base()), doc(base())).classification).toBe(
      STRICTLY_COMPARABLE,
    )
  })

  it('blocks when a strict dimension differs', () => {
    const verdict = classify(RULES, doc(base()), doc(variant('runtime.name', 'llama.cpp')))
    expect(verdict.classification).toBe(NOT_COMPARABLE)
  })

  it('downgrades rather than blocks when only hardware differs', () => {
    const verdict = classify(RULES, doc(base()), doc(variant('system.gpu', 'Another GPU')))
    expect(verdict.classification).toBe(CONDITIONALLY_COMPARABLE)
    expect(verdict.machine_reasons).toContain('system.hardware')
  })

  it('blocks when required provenance is missing on one side', () => {
    const verdict = classify(RULES, doc(base()), doc(variant('reproducibility.iterations')))
    expect(verdict.classification).toBe(NOT_COMPARABLE)
    expect(verdict.machine_reasons).toContain(RULES.insufficient_metadata_reason)
  })

  it('treats a missing second result as not comparable', () => {
    expect(classify(RULES, doc(base()), undefined).classification).toBe(NOT_COMPARABLE)
  })
})
