"""Generate package-manager manifests from a built release artifact.

Usage:
    python scripts/generate_packaging.py --dist dist --output packaging

Install friction directly suppresses submission volume, which is this
project's actual bottleneck: the framework exists, the hardware coverage does
not, and every extra step between "I have an interesting GPU" and "I ran the
benchmark" costs results.

Manifests are **generated from a real artifact**, never hand-written. A
Homebrew formula or a winget manifest carries a version and a SHA-256 of a
specific file; typing those by hand produces a manifest that installs nothing,
or worse, silently pins an old release. Everything here is derived from what
was actually built, so a manifest cannot describe a file that does not exist.

Run in the release workflow after the sdist and wheel are built.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from aihwbench.versions import PACKAGE_VERSION  # noqa: E402

REPO = "webdevsamran/local-ai-hardware-bench"
HOMEPAGE = f"https://github.com/{REPO}"
DESCRIPTION = (
    "Vendor-neutral benchmarking of local AI runtimes across CPUs, GPUs, NPUs and edge accelerators"
)
LICENSE = "Apache-2.0"
NL = chr(10)


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_sdist(dist: pathlib.Path) -> pathlib.Path:
    """The source distribution, which the package managers install from."""
    candidates = sorted(dist.glob("*.tar.gz"))
    if not candidates:
        raise FileNotFoundError(f"no sdist (*.tar.gz) in {dist}; run `python -m build` first")
    if len(candidates) > 1:
        raise ValueError(
            f"more than one sdist in {dist}: {[c.name for c in candidates]}. "
            "Refusing to guess which release these manifests describe."
        )
    return candidates[0]


def homebrew_formula(version: str, url: str, digest: str) -> str:
    """A Homebrew formula installing from the sdist via pip."""
    return NL.join(
        [
            "# Generated by scripts/generate_packaging.py from a built artifact.",
            "# Do not edit by hand: the version and sha256 describe one specific",
            "# release file, and a hand-edited value installs the wrong thing.",
            "class Aihwbench < Formula",
            "  include Language::Python::Virtualenv",
            "",
            f'  desc "{DESCRIPTION}"',
            f'  homepage "{HOMEPAGE}"',
            f'  url "{url}"',
            f'  sha256 "{digest}"',
            f'  license "{LICENSE}"',
            f'  version "{version}"',
            "",
            '  depends_on "python@3.12"',
            "",
            "  def install",
            "    virtualenv_install_with_resources",
            "  end",
            "",
            "  test do",
            '    assert_match version.to_s, shell_output("#{bin}/aihwbench --version")',
            "  end",
            "end",
            "",
        ]
    )


def scoop_manifest(version: str, url: str, digest: str) -> str:
    """A Scoop manifest (Windows), which is JSON."""
    import json

    return (
        json.dumps(
            {
                "version": version,
                "description": DESCRIPTION,
                "homepage": HOMEPAGE,
                "license": LICENSE,
                "url": url,
                "hash": f"sha256:{digest}",
                "depends": "python",
                "installer": {"script": ["python -m pip install --user aihwbench"]},
                "bin": "aihwbench",
                "checkver": {"github": HOMEPAGE},
                "autoupdate": {
                    "url": (f"{HOMEPAGE}/releases/download/v$version/aihwbench-$version.tar.gz")
                },
                "notes": (
                    "Generated from a built artifact by "
                    "scripts/generate_packaging.py; do not edit by hand."
                ),
            },
            indent=4,
        )
        + NL
    )


def winget_manifest(version: str, url: str, digest: str) -> str:
    """A winget installer manifest (YAML, written without a YAML dependency)."""
    return NL.join(
        [
            "# Generated by scripts/generate_packaging.py from a built artifact.",
            "# Do not edit by hand.",
            "PackageIdentifier: webdevsamran.aihwbench",
            f"PackageVersion: {version}",
            "PackageName: AIHWBench",
            "Publisher: webdevsamran",
            f"License: {LICENSE}",
            f"ShortDescription: {DESCRIPTION}",
            f"PackageUrl: {HOMEPAGE}",
            "InstallerType: portable",
            "Installers:",
            "  - Architecture: neutral",
            f"    InstallerUrl: {url}",
            f"    InstallerSha256: {digest.upper()}",
            "ManifestType: singleton",
            "ManifestVersion: 1.6.0",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dist", default="dist", help="Directory holding the built sdist")
    parser.add_argument("--output", default="packaging", help="Where to write manifests")
    parser.add_argument("--version", default=PACKAGE_VERSION)
    args = parser.parse_args(argv)

    dist = pathlib.Path(args.dist)
    try:
        sdist = find_sdist(dist)
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    digest = sha256(sdist)
    url = f"{HOMEPAGE}/releases/download/v{args.version}/{sdist.name}"

    out = pathlib.Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    written = {
        "aihwbench.rb": homebrew_formula(args.version, url, digest),
        "aihwbench.json": scoop_manifest(args.version, url, digest),
        "aihwbench.yaml": winget_manifest(args.version, url, digest),
    }
    for name, text in written.items():
        (out / name).write_text(text, encoding="utf-8")
        print(f"wrote {out / name}")

    print(f"source: {sdist.name}")
    print(f"sha256: {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
