"""Generate the published model-zoo page from the manifest itself.

Usage:
    python scripts/generate_model_zoo_docs.py           # write
    python scripts/generate_model_zoo_docs.py --check   # verify freshness

Generated rather than hand-written for the reason the comparability rubric is:
a licence table that describes a previous version of the manifest is worse
than no table, because a reader will act on it. CI runs this with --check, so
`models/zoo.json` and the published page cannot disagree.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from aihwbench.modelzoo import ZooEntry, load_zoo  # noqa: E402

OUT = ROOT / "docs" / "models" / "zoo.md"
ZOO = ROOT / "models" / "zoo.json"
NL = chr(10)

_SOURCE_PROSE = {
    "gguf-header": (
        "read from the file's own GGUF header (`general.license`), so anyone "
        "holding the file can re-derive it"
    ),
    "ollama-api": "reported by Ollama, which relays the publisher's own statement",
    "declared": (
        "**written by a maintainer.** The format carries no licence field, so "
        "nothing re-checks this against the artifact"
    ),
}

_KIND_PROSE = {
    "weights-sha256": (
        "SHA-256 of the weights file. Identifies the weights and nothing else, "
        "so it is the only kind that can be compared across runtimes."
    ),
    "ollama-manifest-sha256": (
        "SHA-256 of an Ollama manifest, which covers the weights *and* the "
        "template *and* the system prompt. It changes when the template "
        "changes and the weights do not, so it identifies a served "
        "configuration rather than a set of weights."
    ),
}


def _obtain(entry: ZooEntry) -> str:
    kind = entry.source.get("kind")
    if kind == "ollama":
        return f"`ollama pull {entry.source.get('ref')}`"
    if kind == "https":
        return f"[download]({entry.source.get('url')})"
    return "no source is recorded"


def _section(entry: ZooEntry) -> str:
    size = f"{entry.size_bytes / 1e6:.1f} MB" if entry.size_bytes else "unrecorded"
    lines = [
        f"### {entry.name}",
        "",
        f"- **Key**: `{entry.key}`",
        f"- **Format**: {entry.format}"
        + (f", {entry.quantization}" if entry.quantization else "")
        + (f", {entry.parameters} parameters" if entry.parameters else ""),
        f"- **Size**: {size}",
        f"- **Obtain**: {_obtain(entry)}",
        f"- **Verify**: `aihwbench zoo verify {entry.key}`",
    ]

    if entry.license:
        basis = _SOURCE_PROSE.get(entry.license_source or "", entry.license_source or "unstated")
        licence = f"- **Licence**: {entry.license} — {basis}"
        if entry.license_link:
            licence += f". [Terms]({entry.license_link})"
        lines.append(licence)
    else:
        lines.append(
            "- **Licence**: not recorded. The artifact states none and no "
            "maintainer has declared one, so redistribution terms are unknown."
        )

    if entry.checksum:
        lines += [
            f"- **Checksum**: `{entry.checksum}`",
            f"  - {_KIND_PROSE.get(entry.checksum_kind or '', 'kind unstated')}",
        ]
    else:
        lines.append(
            "- **Checksum**: none recorded, so no file can be confirmed to be "
            "the one that was benchmarked."
        )

    if entry.aliases:
        lines.append("- **Also recorded in results as**:")
        lines += [f"  - `{alias}`" for alias in entry.aliases]

    if entry.notes:
        lines += ["", entry.notes]
    return NL.join(lines)


def render() -> str:
    entries = load_zoo(ZOO)
    parts = [
        "# Model zoo",
        "",
        "<!-- Generated by scripts/generate_model_zoo_docs.py from "
        "models/zoo.json. Do not edit by hand. -->",
        "",
        "Every model this project has published a measurement of, with the "
        "licence it is offered under, a checksum to confirm you have the same "
        "file, and the command that gets it.",
        "",
        "## Why this page exists",
        "",
        "A result names a model. That name will not obtain the model, will not "
        "confirm that the file you obtained is the file that was measured, and "
        "says nothing about whether you may redistribute it.",
        "",
        "Both gaps were real here. Four published results measure "
        "`mobilenetv2-12.onnx`; the file had been deleted from the machine "
        "that produced them, nothing recorded where it came from, and all four "
        "record `checksum: null`. The measurements outlived the thing measured.",
        "",
        "And two published checksums for *byte-identical weights* disagreed. "
        "The llama.cpp results hash the weights file; the Ollama results hash "
        "Ollama's manifest, which also covers the template and system prompt. "
        "One field, two kinds of hash, nothing saying which. That is why every "
        "entry below states what its checksum is a hash **of**.",
        "",
        "## Licences are read, not assumed",
        "",
        "A licence is a legal claim about someone else's work, so each one "
        "below records where the claim came from. A licence marked as read "
        "from the artifact can be re-derived by anyone holding the file; "
        "`aihwbench zoo verify` re-reads it and fails if the manifest and the "
        "artifact disagree.",
        "",
        "Nothing here is inferred from a model's name, from a sibling model's "
        "terms, or from the licence of a repository that happens to host the "
        "file. Where a format carries no licence field at all, the entry says "
        "the licence was declared by a maintainer and links the terms it was "
        "taken from, so you can check it yourself.",
        "",
        "**None of this is legal advice, and none of it substitutes for "
        "reading the licence.** Verify the terms before you rely on them.",
        "",
        "## Models",
        "",
    ]
    parts.append((NL * 2).join(_section(entry) for entry in entries))
    parts += [
        "",
        "## Commands",
        "",
        "```bash",
        "aihwbench zoo list              # licences and sources at a glance",
        "aihwbench zoo verify            # check every model this machine can reach",
        "aihwbench zoo fetch <key>       # download, verifying against the checksum",
        "```",
        "",
        "`fetch` hashes the bytes as they arrive and deletes a download whose "
        "hash does not match, rather than leaving the wrong model on disk "
        "where a later benchmark could pick it up.",
        "",
        "`verify` reports three outcomes, and the last two are different: the "
        "file matches, the file **does not** match, or nothing could be "
        "checked. Unchecked is not a pass.",
        "",
    ]
    return NL.join(parts)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.is_file():
            print(f"error: {OUT} is missing; run this script without --check", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(
                f"error: {OUT} is stale. models/zoo.json changed without "
                "regenerating the published page. Run: "
                "python scripts/generate_model_zoo_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT} matches the manifest")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
